### ISSUE TITLE
The function train_bck_Complex_RM_CNN is not found in train_model.py. And, how to cite your work?

### ISSUE THREAD

**Issue by guyucowboy** [ku-milab/MGICNN#2]
Hi, ku-milab
I have two questions to ask you.
The function train_bck_Complex_RM_CNN is not found in train_model.py. How to solve that?
How to cite your work, Multi-scale Gradual Integration Convolutional Neural Network for false positive reduction in pulmonary nodule detection in CT scan?
Thank you very much!
Best regards
Gu Yu

**Comment by bck8888** [comment]
Dear Gu Yu

Thanks for your questions. 
When I modified the code, I modified the def train_bck_Complex_RM_CNN to train_Gradual_Multi_scale_CNN, but I did not modify the test.

We will fix it.

And cite can be found [here](https://arxiv.org/abs/1807.10581).

Thank you.

Best regards

Bum-Chae Kim (bck8888)

**Comment by JunsikChoi** [comment]
Code fixed.
Closing this issue.
