### ISSUE TITLE
Missing function test_patch_extraction

### ISSUE THREAD

**Issue by icech** [ku-milab/MGICNN#6]
hi,
    Line  34 in  CAD_nodule_Detection.py as following,
         btm, mid, top = def_Patch_Extract_.test_patch_extraction(DAT_DATA_Path, CT_scans)
    however,  there is no 'test_patch_extraction' function in def_Patch_Extract_.py, did u forget to add the function ?

**Comment by wltjr1007** [comment]
There has been a major revision to the repository. This issue has been fixed.
